export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL'

export const EVENT_LIST_BY_RATING_REQUEST = 'EVENT_LIST_BY_RATING_REQUEST'
export const EVENT_LIST_BY_RATING_SUCCESS = 'EVENT_LIST_BY_RATING_SUCCESS'
export const EVENT_LIST_BY_RATING_FAIL = 'EVENT_LIST_BY_RATING_FAIL'

export const EVENT_LIST_BY_NEWEST_REQUEST = 'EVENT_LIST_BY_NEWEST_REQUEST'
export const EVENT_LIST_BY_NEWEST_SUCCESS = 'EVENT_LIST_BY_NEWEST_SUCCESS'
export const EVENT_LIST_BY_NEWEST_FAIL = 'EVENT_LIST_BY_NEWEST_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL'

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST'
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS'
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL'
export const EVENT_CREATE_RESET = 'EVENT_CREATE_RESET'

export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST'
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS'
export const EVENT_UPDATE_FAIL = 'EVENT_UPDATE_FAIL'
export const EVENT_UPDATE_RESET = 'EVENT_UPDATE_RESET'

export const EVENT_CREATE_REVIEW_REQUEST = 'EVENT_CREATE_REVIEW_REQUEST'
export const EVENT_CREATE_REVIEW_SUCCESS = 'EVENT_CREATE_REVIEW_SUCCESS'
export const EVENT_CREATE_REVIEW_FAIL = 'EVENT_CREATE_REVIEW_FAIL'
export const EVENT_CREATE_REVIEW_RESET = 'EVENT_CREATE_REVIEW_RESET'

export const EVENT_UPDATE_REVIEW_REQUEST = 'EVENT_UPDATE_REVIEW_REQUEST'
export const EVENT_UPDATE_REVIEW_SUCCESS = 'EVENT_UPDATE_REVIEW_SUCCESS'
export const EVENT_UPDATE_REVIEW_FAIL = 'EVENT_UPDATE_REVIEW_FAIL'
export const EVENT_UPDATE_REVIEW_RESET = 'EVENT_UPDATE_REVIEW_RESET'

export const EVENT_DELETE_REVIEW_REQUEST = 'EVENT_DELETE_REVIEW_REQUEST'
export const EVENT_DELETE_REVIEW_SUCCESS = 'EVENT_DELETE_REVIEW_SUCCESS'
export const EVENT_DELETE_REVIEW_FAIL = 'EVENT_DELETE_REVIEW_FAIL'

export const EVENT_TOP_REQUEST = 'EVENT_TOP_REQUEST'
export const EVENT_TOP_SUCCESS = 'EVENT_TOP_SUCCESS'
export const EVENT_TOP_FAIL = 'EVENT_TOP_FAIL'

export const EVENT_LATEST_REQUEST = 'EVENT_LATEST_REQUEST'
export const EVENT_LATEST_SUCCESS = 'EVENT_LATEST_SUCCESS'
export const EVENT_LATEST_FAIL = 'EVENT_LATEST_FAIL'