export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'

export const ORDER_MY_LIST_REQUEST = 'ORDER_MY_LIST_REQUEST'
export const ORDER_MY_LIST_SUCCESS = 'ORDER_MY_LIST_SUCCESS'
export const ORDER_MY_LIST_FAIL = 'ORDER_MY_LIST_FAIL'
export const ORDER_MY_LIST_RESET = 'ORDER_MY_LIST_RESET'

export const ORDER_MY_LIST_BY_NEWEST_REQUEST = 'ORDER_MY_LIST_BY_NEWEST_REQUEST'
export const ORDER_MY_LIST_BY_NEWEST_SUCCESS = 'ORDER_MY_LIST_BY_NEWEST_SUCCESS'
export const ORDER_MY_LIST_BY_NEWEST_FAIL = 'ORDER_MY_LIST_BY_NEWEST_FAIL'
export const ORDER_MY_LIST_BY_NEWEST_RESET = 'ORDER_MY_LIST_BY_NEWEST_RESET'

export const ORDER_MY_LIST_BY_OLDEST_REQUEST = 'ORDER_MY_LIST_BY_OLDEST_REQUEST'
export const ORDER_MY_LIST_BY_OLDEST_SUCCESS = 'ORDER_MY_LIST_BY_OLDEST_SUCCESS'
export const ORDER_MY_LIST_BY_OLDEST_FAIL = 'ORDER_MY_LIST_BY_OLDEST_FAIL'
export const ORDER_MY_LIST_BY_OLDEST_RESET = 'ORDER_MY_LIST_BY_OLDEST_RESET'

export const ORDER_MY_LIST_BY_PRICE_REQUEST = 'ORDER_MY_LIST_BY_PRICE_REQUEST'
export const ORDER_MY_LIST_BY_PRICE_SUCCESS = 'ORDER_MY_LIST_BY_PRICE_SUCCESS'
export const ORDER_MY_LIST_BY_PRICE_FAIL = 'ORDER_MY_LIST_BY_PRICE_FAIL'
export const ORDER_MY_LIST_BY_PRICE_RESET = 'ORDER_MY_LIST_BY_PRICE_RESET'

export const ORDER_MY_LIST_BY_LATEST_REQUEST = 'ORDER_MY_LIST_BY_LATEST_REQUEST'
export const ORDER_MY_LIST_BY_LATEST_SUCCESS = 'ORDER_MY_LIST_BY_LATEST_SUCCESS'
export const ORDER_MY_LIST_BY_LATEST_FAIL = 'ORDER_MY_LIST_BY_LATEST_FAIL'
export const ORDER_MY_LIST_BY_LATEST_RESET = 'ORDER_MY_LIST_BY_LATEST_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'

export const ORDER_LIST_INCONFIRMED_REQUEST = 'ORDER_LIST_INCONFIRMED_REQUEST'
export const ORDER_LIST_INCONFIRMED_SUCCESS = 'ORDER_LIST_INCONFIRMED_SUCCESS'
export const ORDER_LIST_INCONFIRMED_FAIL = 'ORDER_LIST_INCONFIRMED_FAIL'
export const ORDER_LIST_INCONFIRMED_RESET = 'ORDER_LIST_INCONFIRMED_RESET'

export const ORDER_LIST_CONFIRMED_REQUEST = 'ORDER_LIST_CONFIRMED_REQUEST'
export const ORDER_LIST_CONFIRMED_SUCCESS = 'ORDER_LIST_CONFIRMED_SUCCESS'
export const ORDER_LIST_CONFIRMED_FAIL = 'ORDER_LIST_CONFIRMED_FAIL'
export const ORDER_LIST_CONFIRMED_RESET = 'ORDER_LIST_CONFIRMED_RESET'

export const ORDER_LIST_BY_NEWEST_REQUEST = 'ORDER_LIST_BY_NEWEST_REQUEST'
export const ORDER_LIST_BY_NEWEST_SUCCESS = 'ORDER_LIST_BY_NEWEST_SUCCESS'
export const ORDER_LIST_BY_NEWEST_FAIL = 'ORDER_LIST_BY_NEWEST_FAIL'
export const ORDER_LIST_BY_NEWEST_RESET = 'ORDER_LIST_BY_NEWEST_RESET'

export const ORDER_LIST_BY_OLDEST_REQUEST = 'ORDER_LIST_BY_OLDEST_REQUEST'
export const ORDER_LIST_BY_OLDEST_SUCCESS = 'ORDER_LIST_BY_OLDEST_SUCCESS'
export const ORDER_LIST_BY_OLDEST_FAIL = 'ORDER_LIST_BY_OLDEST_FAIL'
export const ORDER_LIST_BY_OLDEST_RESET = 'ORDER_LIST_BY_OLDEST_RESET'

export const ORDER_LIST_PAID_REQUEST = 'ORDER_LIST_PAID_REQUEST'
export const ORDER_LIST_PAID_SUCCESS = 'ORDER_LIST_PAID_SUCCESS'
export const ORDER_LIST_PAID_FAIL = 'ORDER_LIST_PAID_FAIL'
export const ORDER_LIST_PAID_RESET = 'ORDER_LIST_PAID_RESET'

export const ORDER_LIST_DELIVERED_REQUEST = 'ORDER_LIST_DELIVERED_REQUEST'
export const ORDER_LIST_DELIVERED_SUCCESS = 'ORDER_LIST_DELIVERED_SUCCESS'
export const ORDER_LIST_DELIVERED_FAIL = 'ORDER_LIST_DELIVERED_FAIL'
export const ORDER_LIST_DELIVERED_RESET = 'ORDER_LIST_DELIVERED_RESET'

export const ORDER_CONFIRM_REQUEST = 'ORDER_CONFIRM_REQUEST'
export const ORDER_CONFIRM_SUCCESS = 'ORDER_CONFIRM_SUCCESS'
export const ORDER_CONFIRM_FAIL = 'ORDER_CONFIRM_FAIL'
export const ORDER_CONFIRM_RESET = 'ORDER_CONFIRM_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'